### ISSUE TITLE
electron demo

### ISSUE THREAD

**Issue by frodik13** [ABTSoftware/SciChart.JS.Examples#244]
The demo version of Electron does not start.

I get this error:
```
An unhandled rejection has occurred inside Forge:
Error: Unable to use specified module loaders for ".ts".
at exports.prepare (D:\Projects\SciChart.JS.Examples\Sandbox\scichart-electron-demo\node_modules\rechoir\index.js:58:11)
    at exports.default (D:\Projects\SciChart.JS.Examples\Sandbox\scichart-electron-demo\node_modules\@electron-forge\core\dist\util\forge-config.js:122:25)
    at async Task.task (D:\Projects\SciChart.JS.Examples\Sandbox\scichart-electron-demo\node_modules\@electron-forge\core\dist\api\start.js:43:35)
    at async Task.run (D:\Projects\SciChart.JS.Examples\Sandbox\scichart-electron-demo\node_modules\listr2\dist\index.cjs:978:11)
    at async D:\Projects\SciChart.JS.Examples\Sandbox\scichart-electron-demo\node_modules\p-map\index.js:57:22
```

**Comment by antichaosdb** [comment]
Updating the dependencies as follows seems to fix it
"ts-loader": "^9.5.1",
"ts-node": "^10.9.2",
"typescript": "^5.7.2"

These have been pushed to the example
